export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN', // School Admin
  HEADMASTER = 'HEADMASTER',
  PRINCIPAL = 'PRINCIPAL',
  TEACHER = 'TEACHER',
  STAFF = 'STAFF',
  STUDENT = 'STUDENT',
  PARENT = 'PARENT',
  DRIVER = 'DRIVER',
  AGENT = 'AGENT',
  CUSTOMER_CARE = 'CUSTOMER_CARE',
  HOSTEL_SUPER = 'HOSTEL_SUPER',
  LIBRARIAN = 'LIBRARIAN',
  SHOP_KEEPER = 'SHOP_KEEPER',
  MCM = 'MCM',
  SUPPLIER = 'SUPPLIER'
}