import { Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';

@Injectable()
export class AiDoubtService {
  constructor(private prisma: PrismaService) {}

  async generateEmbedding(text: string): Promise<number[]> {
    // Mock embedding generation (1536 dimensions)
    // In a real scenario, call OpenAI API or similar
    return Array.from({ length: 1536 }, () => Math.random());
  }

  async generateAnswer(prompt: string): Promise<string> {
    // Placeholder for LLM generation
    console.log('Generated Prompt for LLM:', prompt);
    return "This is a simulated AI answer based on the provided textbook context. In a real environment, this text would be generated by an LLM using the context chunks found in the vector database.";
  }

  async solveDoubt(studentId: string, subjectId: string, question: string) {
    const vector = await this.generateEmbedding(question);
    const vectorString = `[${vector.join(',')}]`;

    // Perform similarity search
    const results: any[] = await this.prisma.$queryRaw`
      SELECT content_chunk, page_number
      FROM textbook_embeddings
      WHERE subject_id = ${subjectId}
      ORDER BY vector <=> ${vectorString}::vector
      LIMIT 3;
    `;

    const context = results.map((r) => r.content_chunk);
    const topPage = results.length > 0 ? results[0].page_number : null;

    const prompt = `Context: ${context.join('\n')} Question: ${question} Answer the question using ONLY the provided context.`;
    const answer = await this.generateAnswer(prompt);

    // Save interaction
    const interaction = await this.prisma.aiInteraction.create({
      data: {
        studentId,
        question,
        answer,
        context: context,
        sourcePage: topPage,
      },
    });

    return {
      interactionId: interaction.id,
      answer,
      context,
      sourcePage: topPage,
    };
  }

  async submitFeedback(interactionId: string, isHelpful: boolean) {
    const interaction = await this.prisma.aiInteraction.findUnique({
      where: { id: interactionId },
    });

    if (!interaction) {
      throw new NotFoundException('Interaction not found');
    }

    return this.prisma.aiInteraction.update({
      where: { id: interactionId },
      data: { isHelpful },
    });
  }
}
