import { Injectable } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';

@Injectable()
export class AiDoubtService {
  constructor(private prisma: PrismaService) {}

  async generateEmbedding(text: string): Promise<number[]> {
    // Mock embedding generation (1536 dimensions)
    // In a real scenario, call OpenAI API or similar
    return Array.from({ length: 1536 }, () => Math.random());
  }

  async generateAnswer(prompt: string): Promise<string> {
    // Placeholder for LLM generation
    // In a real scenario, this would call OpenAI's completion API
    // e.g., await openai.chat.completions.create({ messages: [{ role: 'user', content: prompt }] })

    console.log('Generated Prompt for LLM:', prompt);

    return "This is a simulated AI answer based on the provided textbook context. In a real environment, this text would be generated by an LLM using the context chunks found in the vector database.";
  }

  async solveDoubt(studentId: string, subjectId: string, question: string) {
    const vector = await this.generateEmbedding(question);
    const vectorString = `[${vector.join(',')}]`;

    // Perform similarity search using cosine distance (<=> operator)
    // Select top 3 relevant chunks as requested
    const results: any[] = await this.prisma.$queryRaw`
      SELECT content_chunk
      FROM textbook_embeddings
      WHERE subject_id = ${subjectId}
      ORDER BY vector <=> ${vectorString}::vector
      LIMIT 3;
    `;

    // Map results to extracting content_chunk
    const context = results.map((r) => r.content_chunk);

    // Form the prompt
    const prompt = `Context: ${context.join('\n')} Question: ${question} Answer the question using ONLY the provided context.`;

    // Generate answer
    const answer = await this.generateAnswer(prompt);

    return {
      answer,
      context, // Returning context for transparency/debugging
    };
  }
}
